package org.elm.lang.core.lexer

import com.intellij.lexer.FlexAdapter

/**
 * A raw lexer over the lexer generated by Flex. The purpose of this
 * lexer is to provide basic lexing (no special whitespace logic).
 * It can be used in places where a state-less (incremental) lexer is
 * needed by IntelliJ (syntax highlighting), and it can be used as the
 * foundation for a stateful lexer.
 *
 * @see ElmLayoutLexer
 */
class ElmIncrementalLexer : FlexAdapter(_ElmLexer())
