package org.elm.lang.core.lexer

/**
 * A raw lexer over the lexer generated by Flex. The purpose of this
 * lexer is to provide basic lexing (no special whitespace logic)
 * to be used in places where a state-less (incremental) lexer is
 * needed by IntelliJ (syntax highlighting).
 *
 * @see ElmLayoutLexer
 */
class ElmIncrementalLexer : ElmLexer()
