package org.elm.lang.core.parser.manual

import com.intellij.lang.PsiBuilder
import com.intellij.lang.parser.GeneratedParserUtilBase


/**
 * Entry-points for manual/external parse rules to be called by the parser
 * generated by GrammarKit.
 *
 * In general, the reason we need manual parse rules is to handle cases
 * where Elm requires that there be no whitespace between certain tokens
 * (e.g. a "dotted" module name such as `Json.Encode`)
 */
object ElmManualParseRules : GeneratedParserUtilBase() {
    @JvmStatic
    fun parseDotWithoutTrailingWhitespace(builder: PsiBuilder, level: Int) =
            DotWithoutTrailingWhitespaceParser.parse(builder, level)

    @JvmStatic
    fun parseDotWithoutWhitespace(builder: PsiBuilder, level: Int) =
            DotWithoutWhitespaceParser.parse(builder, level)
}
