package org.elm.lang.core.parser.manual;

import com.intellij.lang.PsiBuilder;
import com.intellij.lang.parser.GeneratedParserUtilBase;
import org.elm.lang.core.psi.ElmTypes;

// TODO [kl] convert to Kotlin. (JVM static interop?)


/**
 * Entry-points for manual/external parse rules to be called by the parser
 * generated by GrammarKit.
 */
public class ElmParserUtil extends GeneratedParserUtilBase {

    // case_of_header case_of_branch (case_of_one_or_more_separation case_of_branch)*
    public static boolean parseCaseOf(PsiBuilder builder, int level, Parser header, Parser branch, Parser oneOrMoreSeparations) {
        return new CaseOfParser(header, branch, oneOrMoreSeparations)
                .parse(builder, level);
    }

    // LET inner_value_declaration other_value_declarations IN expression
    public static boolean parseLetIn(PsiBuilder builder, int level, Parser innerValueDeclaration, Parser otherValueDeclarations, Parser expression) {
        return new LetInParser(innerValueDeclaration, otherValueDeclarations, expression)
                .parse(builder, level);
    }

    public static boolean parseUpperCasePath(PsiBuilder builder, int level, Parser upperCaseId) {
        return new PathParser(
                ElmTypes.UPPER_CASE_PATH,
                ElmTypes.UPPER_CASE_IDENTIFIER,
                null,
                upperCaseId,
                null
        )
                .parse(builder, level);
    }

    public static boolean parseMixedCasePath(PsiBuilder builder, int level, Parser upperCaseId, Parser lowerCaseId) {
        return new PathParser(
                ElmTypes.MIXED_CASE_PATH,
                ElmTypes.UPPER_CASE_IDENTIFIER,
                ElmTypes.LOWER_CASE_IDENTIFIER,
                upperCaseId,
                lowerCaseId
        )
                .parse(builder, level);
    }

    public static boolean parseLowerCasePath(PsiBuilder builder, int level, Parser lowerCaseId) {
        return new PathParser(
                ElmTypes.LOWER_CASE_PATH,
                ElmTypes.LOWER_CASE_IDENTIFIER,
                null,
                lowerCaseId,
                null
        )
                .parse(builder, level);
    }

    public static boolean parseFieldAccess(PsiBuilder builder, int level) {
        return new FieldAccessParser()
                .parse(builder, level);
    }

    public static boolean parseEffect(PsiBuilder builder, int level) {
        return new EffectParser()
                .parse(builder, level);
    }
}
