name: Test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      -  name: Cache gradle wrapper
         uses: actions/cache@v1
         with:
            path: ~/.gradle/wrapper
            key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
            restore-keys: |
               ${{ runner.os }}-gradlewrapper-
      -  name: Cache maven
         uses: actions/cache@v1
         with:
            path: ~/.m2/repository/
            key: ${{ runner.os }}-maven-${{ hashFiles('**/*.gradle') }}
            restore-keys: |
               ${{ runner.os }}-maven-

      - name: Run ubuntu tests
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget -q https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip binary-for-linux-64-bit.gz
          chmod +x binary-for-linux-64-bit
          sudo mv binary-for-linux-64-bit /usr/local/bin/elm
          ./gradlew check
      - name: Run windows tests
        if: matrix.os == 'windows-latest'
        run: |
          choco install --yes elm-platform
          ./gradlew check
      - name: Run macOS tests
        if: matrix.os == 'macOS-latest'
        run: |
          brew install elm
          ./gradlew check

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: error-report
          path: build-reports.zip

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
